use crate::matrix::MatrixCell::{Lit, Off};
use crate::matrix::MatrixFrame;
use crate::scroller::MATRIX_SIZE;
use phf::phf_map;

pub static LETTER_FRAMES: phf::Map<char, MatrixFrame<MATRIX_SIZE>> = phf_map! {
    ' ' => MatrixFrame([
        [Off, Off, Off, Off, Off],
        [Off, Off, Off, Off, Off],
        [Off, Off, Off, Off, Off],
        [Off, Off, Off, Off, Off],
        [Off, Off, Off, Off, Off],
    ]),
    'A' => MatrixFrame([
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'B' => MatrixFrame([
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
    ]),
    'C' => MatrixFrame([
        [Off, Off, Lit, Lit, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Off, Lit, Lit, Off],
    ]),
    'D' => MatrixFrame([
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
    ]),
    'E' => MatrixFrame([
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Lit, Off],
    ]),
    'F' => MatrixFrame([
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
    ]),
    'G' => MatrixFrame([
        [Off, Off, Lit, Lit, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Lit, Off],
    ]),
    'H' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'I' => MatrixFrame([
        [Off, Lit, Lit, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Lit, Lit, Off],
    ]),
    'J' => MatrixFrame([
        [Off, Off, Off, Lit, Off],
        [Off, Off, Off, Lit, Off],
        [Off, Off, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
    ]),
    'K' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'L' => MatrixFrame([
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Lit, Off],
    ]),
    'M' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'N' => MatrixFrame([
        [Off, Lit, Off, Off, Lit],
        [Off, Lit, Lit, Off, Lit],
        [Off, Lit, Off, Lit, Lit],
        [Off, Lit, Off, Off, Lit],
        [Off, Lit, Off, Off, Lit],
    ]),
    'O' => MatrixFrame([
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
    ]),
    'P' => MatrixFrame([
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Off, Off, Off],
    ]),
    'Q' => MatrixFrame([
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Lit, Off],
    ]),
    'R' => MatrixFrame([
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'S' => MatrixFrame([
        [Off, Off, Lit, Lit, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Off, Lit, Off],
        [Off, Lit, Lit, Off, Off],
    ]),
    'T' => MatrixFrame([
        [Off, Lit, Lit, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
    ]),
    'U' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Lit, Off],
    ]),
    'V' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
    ]),
    'W' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Lit, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'X' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
    ]),
    'Y' => MatrixFrame([
        [Off, Lit, Off, Lit, Off],
        [Off, Lit, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Off, Lit, Off, Off],
    ]),
    'Z' => MatrixFrame([
        [Off, Lit, Lit, Lit, Off],
        [Off, Off, Off, Lit, Off],
        [Off, Off, Lit, Off, Off],
        [Off, Lit, Off, Off, Off],
        [Off, Lit, Lit, Lit, Off],
    ]),
};
